[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
hex = "0.4.3"
openssl = "0.10.68"
regex = "1.11.1"
serde = "1.0.215"
serde_json = "1.0.133"